### ISSUE TITLE
ImportError: cannot import name 'select_working_views_by_overlap' from 'utils.view_select'

### ISSUE THREAD

**Issue by YuhsiHu** [liuyuan-pal/NeuRay#11]
Thank you for your sharing!
I download the nerf_synthetic dataset and your pre-trained model. When I run 

> python render.py --cfg configs/gen/neuray_gen_depth.yaml --database nerf_synthetic/lego/black_800 --pose_type eval

There is an error:

> Traceback (most recent call last):
  File "render.py", line 12, in <module>
    from network.renderer import name2network
  File "/home/hyx/NeuRay/network/renderer.py", line 21, in <module>
    from utils.view_select import compute_nearest_camera_indices, select_working_views, select_working_views_by_overlap
ImportError: cannot import name 'select_working_views_by_overlap' from 'utils.view_select' 

I  found that the function 'select_working_views_by_overlap' is commented. So I uncomment that and run again. But there is another error:

> Traceback (most recent call last):
  File "render.py", line 210, in <module>
    render_video_gen(flags.database_name, cfg_fn=flags.cfg, pose_type=flags.pose_type, pose_fn=flags.pose_fn,
  File "render.py", line 113, in render_video_gen
    ref_ids_list = select_working_views_db(database, ref_ids_all, que_poses, render_cfg['min_wn'])
  File "/home/hyx/NeuRay/utils/view_select.py", line 86, in select_working_views_db
    indices = select_working_views(ref_poses, que_poses, work_num, exclude_self)
  File "/home/hyx/NeuRay/utils/view_select.py", line 21, in select_working_views
    dists = np.linalg.norm(ref_cam_pts[None, :, :] - render_cam_pts[:, None, :], 2, 2) # qn,rfn
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Could you please help me solve this problem? Thank you for your time!

**Comment by liuyuan-pal** [comment]
Thanks for pointing this out! I've updated the code and it will work now.
I mistakenly included the deprecated `select_working_views_by_overlap` in the code.

**Comment by YuhsiHu** [comment]
Thanks. I clone the repo again and see your update. However, there is still an error when I run:

> python render.py --cfg configs/gen/neuray_gen_depth.yaml --database nerf_synthetic/lego/black_800 --pose_type eval

The IndexError is:  

> Traceback (most recent call last):
  File "render.py", line 210, in <module>
    render_video_gen(flags.database_name, cfg_fn=flags.cfg, pose_type=flags.pose_type, pose_fn=flags.pose_fn,
  File "render.py", line 113, in render_video_gen
    ref_ids_list = select_working_views_db(database, ref_ids_all, que_poses, render_cfg['min_wn'])
  File "/home/hyx/NeuRay/utils/view_select.py", line 86, in select_working_views_db
    indices = select_working_views(ref_poses, que_poses, work_num, exclude_self)
  File "/home/hyx/NeuRay/utils/view_select.py", line 21, in select_working_views
    dists = np.linalg.norm(ref_cam_pts[None, :, :] - render_cam_pts[:, None, :], 2, 2) # qn,rfn
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

**Comment by liuyuan-pal** [comment]
It's a little bit weird. Maybe you can insert a breakpoint here
https://github.com/liuyuan-pal/NeuRay/blob/a877129a76dc7ef6527254e7e6e84ff808f6322f/render.py#L113
and you may check the `len(ref_ids_all)`. The size should be 100. Otherwise, you may check your dataset path is consistent with the README.md or not.
